# .streamlit/secrets.toml
# This file contains sensitive information such as API keys.
GROQ_API_KEY = "API_KEYS"
TAVILY_API_KEY = "API_KEYS"
GROQ_API_KEY = "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"
TAVILY_API_KEY = "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"
