<<<<<<< HEAD
GROQ_API_KEY = "API_KEYS"
TAVILY_API_KEY = "API_KEYS"
=======
GROQ_API_KEY = "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"
TAVILY_API_KEY = "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"
>>>>>>> b4af790e (Updated with new agent and model)
